### PR TITLE
Nkrabben/issue41

### PR DESCRIPTION
**Pull request by nkrabben**
Address #40 and #41

Also made a similar update to the hdd script since it could have the same problem

### CODE REVIEW

**Comment by arhonemus** [comment]
added src. to import digarch_scripts to appease pytest
```diff
diff --git a/tests/test_report_ftk_extents.py b/tests/test_report_ftk_extents.py
index 1a200e2..ecdf026 100644
--- a/tests/test_report_ftk_extents.py
+++ b/tests/test_report_ftk_extents.py
@@ -1,4 +1,4 @@
-import digarch_scripts.report.report_ftk_extents as rfe
+import src.digarch_scripts.report.report_ftk_extents as rfe
 import pytest
 import json
 try:
diff --git a/tests/test_report_hdd_extents.py b/tests/test_report_hdd_extents.py
index f2ce88e..ff7cef8 100644
--- a/tests/test_report_hdd_extents.py
+++ b/tests/test_report_hdd_extents.py
@@ -1,4 +1,4 @@
-import digarch_scripts.report.report_hdd_extents as rhe
+import src.digarch_scripts.report.report_hdd_extents as rhe
 import pytest
 import shutil
 import re

```

**Review by arhonemus — COMMENTED** [review]
Tested with pytest and good to go with my suggestions.
(I'm having issues with nox version of python 3.10 -11. Error that image is x86 and should be ARM. Trying reset/resinstall didn't help.)

**Comment by nkrabben** [comment]
I'm assuming this is some kind of Apple M1 related issue. Will look into.

**Comment by nkrabben** [comment]
Now successfully creates reports for both collections.

I didn't create a test for this particular scenario since I removed all usage of `.split('/')`

**Review by arhonemus — APPROVED** [review]

**Pull request merged**
